name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: ['7.4', '8.0']
        dependency-version: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: fileinfo, intl, sqlite3, pdo_sqlite, pdo_mysql
        tools: composer:v2
        coverage: pcov

    - name: Setup Problem Matches
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install Composer dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist --no-suggest

    - name: Create tests database
      run: php -r "touch('database'.DIRECTORY_SEPARATOR.'database.sqlite');"

    - name: PHPUnit Testing
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/pest --coverage

    - name: Build
      env:
        APP_ENV: development
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php exchange-notify app:build --build-version=0.0

    - name: Build Check
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php builds/exchange-notify --version
